macro (yaga_sources)
  file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
  foreach (_src ${ARGN})
      if (_relPath)
          list (APPEND SRCS "${_relPath}/${_src}")
      else()
          list (APPEND SRCS "${_src}")
      endif()
  endforeach()
  if (_relPath)
      # propagate SRCS to parent directory
      set (SRCS ${SRCS} PARENT_SCOPE)
  endif()
endmacro()

macro (yaga_headers)
  file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
  foreach (_src ${ARGN})
      if (_relPath)
          list (APPEND HEADERS "${_relPath}/${_src}")
      else()
          list (APPEND HEADERS "${_src}")
      endif()
  endforeach()
  if (_relPath)
      # propagate HEADERS to parent directory
      set (HEADERS ${HEADERS} PARENT_SCOPE)
  endif()
endmacro()

macro (yaga_ui)
  file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
  foreach (_src ${ARGN})
      if (_relPath)
          list (APPEND UI "${_relPath}/${_src}")
      else()
          list (APPEND UI "${_src}")
      endif()
  endforeach()
  if (_relPath)
      # propagate UI to parent directory
      set (UI ${UI} PARENT_SCOPE)
  endif()
endmacro()